insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony A7 mark III body', '24.2', 'full-frame', '10fps', '10','2', 1);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony A7 mark IV body', '33.0', 'full-frame', '10fps', '10','2', 2); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony A7R V body', '61.0', 'full-frame', '10fps', '10','2', 3); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony A6100 body', '24.2', 'APS-C', '11fps', '8','1', 4); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony A6400 body', '24.2', 'APS-C', '10fps', '8','1', 5); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony A6600 body', '24.2', 'APS-C', '11fps', '10','1', 6); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony A6700 body', '27.0', 'APS-C', '10fps', '10','1', 7); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony vlog camera ZV-E10 body', '24.2', 'APS-C', '8fps', '8','1', 8); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony alpha a1', '50.1', 'full-frame', '30fps', '10','2', 9); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony FX3 body', '10.2', 'CMOS', '10fps', '10','2', 10);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony FX30 body', '26.0', 'APS-C', '10fps', '14','2', 11);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony A7C2 zilver', '33.0', 'full-frame', '10fps', '10','1', 12); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony a7c', '33.0', 'full-frame', '10fps', '10','1', 13); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony a9III', '24.6', 'full-frame', '10fps', '10','2', 14); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony zv-e1', '24.3', 'APS-C', '10fps', '10','1', 15); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony Cybershot DSC-RX10 mark IV', '20.1', 'full-frame', '24fps', '8','1', 16); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony Cybershot DSC-RX100 mark III', '20.1', 'full-frame', '10fps', '8','1', 17); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony Cybershot DSC-RX100 mark VA', '20.1', 'full-frame', '24fps', '8','1', 18); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony Cybershot DSC-RX100 mark VII', '20.1', 'full-frame', '20fps', '8','1', 19); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Sony vlog camera ZV-1', '24.2', 'APS-C', '10fps', '8','1', 20);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon EOS R6 body', '24.2', 'full-frame', '20fps', '14','2', 21); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon EOS R6 mark II body', '20.1', 'full-frame', '40fps', '10','2', 22); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon EOS R7 body', '32.5', 'APS-C', '30fps', '14','2', 23); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon EOS R8 body', '24.2', 'full-frame', '30fps', '10','1', 24); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon EOS R10 body', '24.2', 'APS-C', '23fps', '14','1', 25); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon EOS 5D Mark IV body', '30.4', 'full-frame', '7fps', '8','2', 26); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon EOS 6D mark II body', '26.2', 'full-frame', '6.5fps', '8','1', 27); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon EOS 250D body zwart', '24.1', 'APS-C', '10fps', '8','1', 28); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon EOS 850D Body', '24.1', 'APS-C', '7fps', '14','1', 29);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon EOS 2000D body', '24.1', 'APS-C', '3fps', '14','1', 30);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon Powershot G1X mark III', '24.2', 'APS-C', '7fps', '14','1', 31);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon Powershot G7X mark III zwart', '20.1', 'full-frame', '10fps', '8','1', 32);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon Powershot SX70 HS', '20.3', 'full-frame', '10fps', '8','1', 33);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Canon Powershot SX740 HS zwart', '20.3', 'full-frame', '10fps', '8','1', 34);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon D780 body', '24.5', 'full-frame', '10fps', '10','2', 35);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon Z5 body', '24.3', 'full-frame', '10fps', '14','2', 36);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon Z6 II body', '24.5', 'full-frame', '14fps', '12','2', 37);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon Z8 body', '45.7', 'full-frame', '120fps', '10','2', 38);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon Z9 body', '45.7', 'full-frame', '120fps', '10','2', 39);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon Z50 body zwart', '20.9', 'APS-C', '11fps', '14','1', 40);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon Z30 body', '20.8', 'full-frame', '11fps', '14','1', 41);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon D7500 Body', '20.9', 'APS-C', '8fps', '14','1', 42);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon D6 Body', '20.8', 'full-frame', '14fps', '14','2', 43);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon Coolpix P1000', '16.0', 'full-frame', '7fps', '12','1', 44); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Nikon Coolpix P950', '16.0', 'full-frame', '30fps', '8','1', 45); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic HC-V785', '12.8', 'BSI', '28fps', '8','1', 46);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic HC-V808', '14.0', 'CMOS', '50fps', '8','1', 47);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic HC-VX1EG', '25.9', 'BSI', '60fps', '8','1', 48); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix DC-BS1HE', '24.2', 'CMOS', '60fps', '10','2', 49); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix DC-G9 body', '20.3', 'MFT', '60fps', '10','2', 50); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix DC-G9II body', '25.3', 'MFT', '75fps', '10','2', 51); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic LUMIX DC-G90 body', '20.3', 'MFT', '9fps', '8','1', 52); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix DC-GH6 body', '25.3', 'MFT', '10fps', '10','2', 53); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix DC-S5 body', '24.2', 'full-frame', '10fps', '10','2', 54); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix DC-S5 IIX body', '24.0', 'full-frame', '30fps', '10','2', 55);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix DC-TZ200D', '20.1', 'CMOS', '10fps', '8','1', 56); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix DMC-FZ2000', '20.1', 'full-frame', '12fps', '8','1', 57); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic LUMIX DMC-G80 body', '16.0', 'MFT', '30fps', '8','1', 58); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix FZ-330', '12.1', 'CMOS', '12fps', '12','1', 59); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix G70 body', '16.0', 'MFT', '8fps', '8','1', 60); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Panasonic Lumix G91', '20.3', 'MFT', '9fps', '8','1', 61); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Fujifilm GFX 50S II body', '51.4', 'full-frame', '3fps', '14','2', 62); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Fujifilm GFX 100 II', '102.0', 'full-frame', '8fps', '10','2', 63); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Fujifilm X-H2 body', '40.2', 'APS-C', '15fps', '10','2', 64);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Fujifilm X-S10 body', '26.0', 'APS-C', '20fps', '8','1', 65);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Fujifilm X-S20 body', '26.1', 'APS-C', '30fps', '10','1', 66); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Fujifilm X-T5 body', '40,2', 'APS-C', '15fps', '10','2', 67); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Fujifilm X-T30 II body', '26.1', 'APS-C', '30fps', '10','2', 68); 
insert into camera (name, product_id) values ('Leica 10301 MP 0.72 chroom', 69); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Leica 10854 SL2 Body', '47.0', 'full-frame', '20fps', '10','2', 70); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Leica 10880 SL2-S Body', '24.0', 'full-frame', '25fps', '10','2', 71); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Leica 19054 Q2 Ghost', '47.3', 'full-frame', '10fps', '14','1', 72); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Leica 19120 V-LUX 5', '20.1', 'full-frame', '30fps', '8','1', 73); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Leica 20211 M11-P body', '60.0', 'full-frame', '4.5fps', '14','1', 74); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Olympus E-P7 Body', '20.3', 'MFT', '8.7fps', '12','1', 75); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Olympus OM-D E-M10 mark IV Body', '20.0', 'MFT', '15fps', '12','1', 76); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('OM SYSTEM OM-1 body', '20.4', 'MFT', '120fps', '14','2', 77);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('OM SYSTEM OM-5 body', '20.4', 'MFT', '30fps', '8','1',78);
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Pentax 645Z Body', '51.4', 'full-frame', '3fps', '14','2', 79); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Pentax K-1 Mark II body', '36.4', 'full-frame', '6.4fps', '14','2', 80); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Pentax K-3 Mark III body', '25.7', 'full-frame', '12fps', '14','1', 81); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Pentax KF Body', '24.0', 'full-frame', '6fps', '14','2', 82); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Hasselblad X1D-50c body', '50.0', 'CMOS', '2.7fps', '16','1', 83); 
insert into camera (name, megapixels, sensor, fps, bitrate, geheugenkaartslots, product_id) values ('Hasselblad X2D 100c body', '100.0', 'full-frame', '3.3fps', '16','1', 84);